import type { CompetitionListing } from "@/lib/types";

export const DESIGN_CATEGORIES = [
  "全部类别", "建筑设计", "景观设计", "城市设计", "室内设计", "家具设计",
  "产品设计", "工业设计", "平面设计", "品牌设计", "包装设计", "交互与UI/UX",
  "服务设计", "时尚与纺织", "珠宝设计", "交通工具", "照明设计",
  "展陈与装置", "摄影与影像", "游戏与数字媒体", "社会创新", "可持续设计",
];

export const COMPETITION_TYPES = [
  "全部类型", "概念竞赛", "真实项目", "作品奖项", "学生竞赛",
  "Open Call", "政府征集", "驻留与奖学金",
];

const checked = "2026-06-14";

export const competitionSources = [
  { name: "ArchDaily Competitions", url: "https://www.archdaily.com/search/competitions", note: "建筑、城市与公开征集" },
  { name: "Competitions.archi", url: "https://competitions.archi/cat/all-competitions/", note: "国际建筑竞赛持续更新" },
  { name: "UIA Competitions", url: "https://www.uia-architectes.org/en/competitions/search/", note: "国际建筑师协会核验项目" },
  { name: "Designboom Competitions", url: "https://www.designboom.com/competitions/design/", note: "产品、平面、建筑与跨学科设计" },
  { name: "Graphic Competitions", url: "https://graphiccompetitions.com/", note: "海报、插画、摄影与视觉传播" },
  { name: "ASLA Opportunities", url: "https://www.asla.org/resources/practitioners/rfqs-and-opportunities", note: "景观设计与专业机会" },
];

export const competitions: CompetitionListing[] = [
  {
    id: "pohang-museum-2026",
    title: "International Design Competition for Pohang Museum",
    translatedTitle: "韩国浦项博物馆国际设计竞赛",
    organizer: "Pohang City",
    country: "韩国", countryCode: "KR", language: "韩语 / 英语",
    categories: ["建筑设计", "城市设计", "展陈与装置"], competitionType: "真实项目",
    deadline: "2026-09-07", daysLeft: 85, entryFee: 0, feeCurrency: "KRW",
    prize: "获胜者获得设计服务权", prizeValueUsd: 0,
    eligibility: ["国际竞赛", "需按官方专业资格要求注册", "团队可参加"], teamAllowed: true,
    summary: "浦项市为新博物馆公开征集设计方案，目标是建立保存、研究和展示城市历史的文化平台。",
    sourceGrade: "A",
    sources: [
      { name: "浦项博物馆竞赛官网", type: "official", url: "http://www.pohang-muse.kr", verified: true },
      { name: "ArchDaily 公告", type: "media", url: "https://www.archdaily.com/1042154/open-call-international-design-competition-for-pohang-museum", verified: true },
    ],
    lastChecked: checked, featured: true,
    brief: "International Design Competition for Pohang Museum. Organized by Pohang City. Registration closes July 20, 2026 and submissions close September 7, 2026. Entry is free. The winner receives design service rights. Consult the official website for professional qualification and deliverable requirements.",
  },
  {
    id: "light-of-tomorrow-2026",
    title: "Light of Tomorrow – International VELUX Award 2026",
    translatedTitle: "Light of Tomorrow 2026 国际建筑学生奖",
    organizer: "VELUX / UIA",
    country: "国际", countryCode: "INT", language: "英语",
    categories: ["建筑设计", "照明设计", "可持续设计"], competitionType: "学生竞赛",
    deadline: "2026-10-01", daysLeft: 109, entryFee: -1, feeCurrency: "EUR",
    prize: "总奖金 €33,000，8支获奖团队", prizeValueUsd: 36000,
    eligibility: ["全球建筑学生", "需教师指导", "个人或团队"], teamAllowed: true,
    summary: "鼓励全球建筑学生研究自然光在建筑和日常生活中的作用，获奖者将参加欧洲工作坊与颁奖活动。",
    sourceGrade: "A",
    sources: [{ name: "UIA 官方竞赛页面", type: "association", url: "https://www.uia-architectes.org/en/competition/light-of-tomorrow-international-velux-award-2026/", verified: true }],
    lastChecked: checked, featured: true,
    brief: "Light of Tomorrow – International VELUX Award 2026 invites architecture students worldwide to investigate daylight in architecture and everyday life. The prize fund is EUR 33,000 across eight winning teams. Verify registration and submission dates on the official UIA competition page.",
  },
  {
    id: "unbuilt-award-2026",
    title: "Buildner’s Unbuilt Award 2026",
    translatedTitle: "Buildner 2026 未建成建筑奖",
    organizer: "Buildner",
    country: "国际", countryCode: "INT", language: "英语",
    categories: ["建筑设计", "城市设计", "室内设计"], competitionType: "作品奖项",
    deadline: "2026-10-20", daysLeft: 128, entryFee: -1, feeCurrency: "EUR",
    prize: "总奖金 €100,000", prizeValueUsd: 109000,
    eligibility: ["全球开放", "未建成项目", "个人或团队"], teamAllowed: true,
    summary: "面向全球未建成建筑项目的大型奖项，奖金高，但报名费用会随阶段上涨。",
    sourceGrade: "B",
    sources: [{ name: "Competitions.archi 条目", type: "media", url: "https://competitions.archi/page/4/", verified: true }],
    lastChecked: checked,
    brief: "Buildner’s Unbuilt Award 2026 celebrates unbuilt architectural ideas worldwide. Total prize EUR 100,000. Submission deadline October 20, 2026 and registration deadline September 23, 2026. Entry fees vary by registration stage.",
  },
  {
    id: "microhome-2026",
    title: "Kingspan MICROHOME 2026",
    translatedTitle: "Kingspan MICROHOME 2026 微型住宅竞赛",
    organizer: "Buildner / Kingspan",
    country: "国际", countryCode: "INT", language: "英语",
    categories: ["建筑设计", "室内设计", "可持续设计"], competitionType: "概念竞赛",
    deadline: "2026-11-02", daysLeft: 141, entryFee: -1, feeCurrency: "EUR",
    prize: "总奖金 €100,000", prizeValueUsd: 109000,
    eligibility: ["全球开放", "学生与专业人士", "个人或团队"], teamAllowed: true,
    summary: "第11届微型住宅竞赛，探索紧凑生活、可持续性与住宅基本需求。",
    sourceGrade: "B",
    sources: [{ name: "Competitions.archi 条目", type: "media", url: "https://competitions.archi/page/4/", verified: true }],
    lastChecked: checked,
    brief: "Kingspan MICROHOME 2026 challenges designers to reimagine compact sustainable living. Total prize EUR 100,000. Submission deadline November 2, 2026. Registration fees vary by stage.",
  },
  {
    id: "ruinas-de-quilmes",
    title: "RUINAS DE QUILMES",
    translatedTitle: "阿根廷 Quilmes 遗址露天博物馆竞赛",
    organizer: "Terraviva",
    country: "阿根廷", countryCode: "AR", language: "英语",
    categories: ["建筑设计", "景观设计", "遗产保护"], competitionType: "概念竞赛",
    deadline: "2026-10-16", daysLeft: 124, entryFee: -1, feeCurrency: "EUR",
    prize: "奖金最高 US$9,000", prizeValueUsd: 9000,
    eligibility: ["全球开放", "个人或团队", "学生可参加"], teamAllowed: true,
    summary: "将 Quilmes 神圣城市重新构想为当代露天博物馆，包括景观介入与新游客中心。",
    sourceGrade: "B",
    sources: [{ name: "Competitions.archi 条目", type: "media", url: "https://competitions.archi/page/4/", verified: true }],
    lastChecked: checked,
    brief: "RUINAS DE QUILMES invites international proposals for an open-air museum, landscape interventions, and a visitor centre in Argentina. Prize up to USD 9,000. Deadline October 16, 2026. Verify current fee on the organizer page.",
  },
  {
    id: "unbox-2026",
    title: "UNBOX 2026 Architecture Competition",
    translatedTitle: "UNBOX 2026 国际建筑概念竞赛",
    organizer: "Volume Zero",
    country: "国际", countryCode: "INT", language: "英语",
    categories: ["建筑设计", "概念研究"], competitionType: "概念竞赛",
    deadline: "2026-12-03", daysLeft: 172, entryFee: -1, feeCurrency: "USD",
    prize: "总奖金 US$10,000", prizeValueUsd: 10000,
    eligibility: ["全球开放", "学生与专业人士", "个人或团队"], teamAllowed: true,
    summary: "重新思考共享环境的“DNA”，面向全球创作者的开放概念竞赛。",
    sourceGrade: "B",
    sources: [{ name: "Competitions.archi 条目", type: "media", url: "https://competitions.archi/page/4/", verified: true }],
    lastChecked: checked,
    brief: "UNBOX 2026 by Volume Zero asks participants to rethink the DNA of shared environments. Open worldwide. USD 10,000 prize. Submission deadline December 3, 2026. Verify current registration fee on the organizer page.",
  },
  {
    id: "pavilion-atlas-2026",
    title: "Pavilion Atlas 2026",
    translatedTitle: "Pavilion Atlas 2026 国际亭子设计竞赛",
    organizer: "Buildner",
    country: "国际", countryCode: "INT", language: "英语",
    categories: ["建筑设计", "展陈与装置"], competitionType: "概念竞赛",
    deadline: "2026-10-19", daysLeft: 127, entryFee: -1, feeCurrency: "EUR",
    prize: "总奖金 €20,000", prizeValueUsd: 21800,
    eligibility: ["全球开放", "个人或团队"], teamAllowed: true,
    summary: "通过亭子表达场所的历史、价值和未来身份，强调清晰有力的空间叙事。",
    sourceGrade: "B",
    sources: [{ name: "Competitions.archi 条目", type: "media", url: "https://competitions.archi/page/4/", verified: true }],
    lastChecked: checked,
    brief: "Pavilion Atlas 2026 asks designers to use a pavilion to express the story, values, and identity of place. EUR 20,000 prize. Submission deadline October 19, 2026.",
  },
  {
    id: "pohang-hold-place",
    title: "HOLD THE PLACE – 16th International Design Contest",
    translatedTitle: "HOLD THE PLACE 第16届国际设计竞赛",
    organizer: "Trieste Contemporanea",
    country: "意大利", countryCode: "IT", language: "英语",
    categories: ["产品设计", "家具设计", "展陈与装置"], competitionType: "Open Call",
    deadline: "2026-07-05", daysLeft: 21, entryFee: -1, feeCurrency: "EUR",
    prize: "多项特别奖与展览机会", prizeValueUsd: 0,
    eligibility: ["国际开放", "按官方年龄与地区规则", "个人参赛"], teamAllowed: false,
    summary: "由 Trieste Contemporanea 主办、ADI 与中欧倡议支持的国际设计公开征集。",
    sourceGrade: "B",
    sources: [{ name: "Competitions.archi 条目", type: "media", url: "https://competitions.archi/cat/all-competitions/", verified: true }],
    lastChecked: checked,
    brief: "HOLD THE PLACE is the 16th International Design Contest by Trieste Contemporanea, under the patronage of ADI and the Central European Initiative. Submission deadline July 5, 2026. Review the official rules for eligibility and prizes.",
  },
  {
    id: "poster-for-tomorrow",
    title: "Poster for Tomorrow 2026–2027: Dignity",
    translatedTitle: "Poster for Tomorrow 2026–2027“尊严”海报竞赛",
    organizer: "4 Tomorrow Association",
    country: "法国", countryCode: "FR", language: "多语言",
    categories: ["平面设计", "社会创新"], competitionType: "Open Call",
    deadline: "2026-07-20", daysLeft: 36, entryFee: -1, feeCurrency: "EUR",
    prize: "入选展览与国际传播", prizeValueUsd: 0,
    eligibility: ["全球设计师", "个人参赛", "原创海报"], teamAllowed: false,
    summary: "第14届国际社会议题海报竞赛，以“尊严”为主题探讨普遍人权。",
    sourceGrade: "B",
    sources: [{ name: "Graphic Competitions 公告", type: "media", url: "https://graphiccompetitions.com/graphic-design/poster-for-tomorrow-2026-2027-international-design-competition", verified: true }],
    lastChecked: checked, featured: true,
    brief: "Poster for Tomorrow 2026–2027 invites designers worldwide to create an original poster on the theme Dignity. Deadline July 20, 2026. Review the organizer rules for file format, fee, and exhibition selection.",
  },
  {
    id: "art-on-climate-2026",
    title: "Art on Climate International Illustration Competition",
    translatedTitle: "Art on Climate 国际插画竞赛",
    organizer: "Art on Climate",
    country: "国际", countryCode: "INT", language: "英语",
    categories: ["平面设计", "摄影与影像", "社会创新"], competitionType: "Open Call",
    deadline: "2026-07-31", daysLeft: 47, entryFee: -1, feeCurrency: "USD",
    prize: "现金奖与国际展示，详见官方规则", prizeValueUsd: 0,
    eligibility: ["全球开放", "插画创作者", "按年龄组评审"], teamAllowed: false,
    summary: "面向全球插画创作者的气候主题比赛，鼓励以视觉叙事回应环境议题。",
    sourceGrade: "B",
    sources: [{ name: "Designboom 竞赛列表", type: "media", url: "https://www.designboom.com/competitions/design/", verified: true }],
    lastChecked: checked,
    brief: "Art on Climate International Illustration Competition calls for visual responses to climate change. The listed deadline is July 31, 2026. Confirm categories, prizes, and submission rules through the linked competition listing.",
  },
  {
    id: "international-design-awards-2026",
    title: "International Design Awards 2026",
    translatedTitle: "IDA 2026 国际设计奖",
    organizer: "International Design Awards",
    country: "美国", countryCode: "US", language: "英语",
    categories: ["建筑设计", "室内设计", "产品设计", "平面设计", "时尚与纺织"], competitionType: "作品奖项",
    deadline: "2026-08-15", daysLeft: 62, entryFee: -1, feeCurrency: "USD",
    prize: "年度奖、国际传播与颁奖活动", prizeValueUsd: 0,
    eligibility: ["全球专业人士", "学生设独立组别", "已完成或概念作品"], teamAllowed: true,
    summary: "覆盖建筑、室内、产品、平面和时尚的综合国际奖项，收费较高，适合已有成熟作品。",
    sourceGrade: "A",
    sources: [{ name: "IDA 官方网站", type: "official", url: "https://www.idesignawards.com/", verified: true }],
    lastChecked: checked,
    brief: "International Design Awards 2026 is open for architecture, interior, product, graphic, and fashion submissions. Regular deadline August 15, 2026. Entry fees vary by category and entrant type. Review official eligibility and fee tables.",
  },
  {
    id: "european-product-design-award",
    title: "European Product Design Award 2026",
    translatedTitle: "2026欧洲产品设计奖",
    organizer: "European Product Design Award",
    country: "欧洲", countryCode: "EU", language: "英语",
    categories: ["产品设计", "工业设计", "家具设计"], competitionType: "作品奖项",
    deadline: "2026-08-09", daysLeft: 56, entryFee: -1, feeCurrency: "EUR",
    prize: "国际荣誉、曝光与获奖者推广", prizeValueUsd: 0,
    eligibility: ["全球设计师", "专业人士", "产品类别广泛"], teamAllowed: true,
    summary: "面向全球产品设计师，强调创造力、功能性与创新，覆盖多种生活和工业产品类别。",
    sourceGrade: "A",
    sources: [{ name: "EPDA 官方网站", type: "official", url: "https://www.productdesignaward.eu/", verified: true }],
    lastChecked: checked,
    brief: "European Product Design Award 2026 is open to designers worldwide across product categories. Regular deadline August 9, 2026. Fees and category requirements vary; consult the official site.",
  },
  {
    id: "muse-design-awards-2026",
    title: "MUSE Design Awards 2026 Season 2",
    translatedTitle: "MUSE 2026设计奖第二季",
    organizer: "International Awards Associate",
    country: "美国", countryCode: "US", language: "英语",
    categories: ["建筑设计", "室内设计", "产品设计", "照明设计", "包装设计"], competitionType: "作品奖项",
    deadline: "2026-07-09", daysLeft: 25, entryFee: -1, feeCurrency: "USD",
    prize: "奖杯、认证与国际媒体曝光", prizeValueUsd: 0,
    eligibility: ["全球专业人士", "多设计类别", "已完成或概念作品"], teamAllowed: true,
    summary: "综合商业设计奖项，覆盖建筑、室内、产品、照明、包装和概念设计。",
    sourceGrade: "A",
    sources: [{ name: "MUSE Design Awards 官方网站", type: "official", url: "https://design.museaward.com/", verified: true }],
    lastChecked: checked,
    brief: "MUSE Design Awards 2026 Season 2 covers architecture, interior, product, lighting, packaging, and conceptual design. The final deadline shown is July 9, 2026. Entry fees vary.",
  },
  {
    id: "rome-design-awards-2026",
    title: "Rome Design Awards 2026 Season 2",
    translatedTitle: "2026罗马设计奖第二季",
    organizer: "Rome Design Awards",
    country: "意大利", countryCode: "IT", language: "英语",
    categories: ["包装设计", "建筑设计", "家具设计", "产品设计", "照明设计", "室内设计"], competitionType: "作品奖项",
    deadline: "2026-09-30", daysLeft: 108, entryFee: -1, feeCurrency: "USD",
    prize: "年度荣誉、奖杯与国际宣传", prizeValueUsd: 0,
    eligibility: ["全球专业人士", "学生组别", "多设计类别"], teamAllowed: true,
    summary: "覆盖空间、产品、家具、灯光和包装的国际商业设计奖项，设多个报名阶段。",
    sourceGrade: "A",
    sources: [{ name: "Rome Design Awards 官方网站", type: "official", url: "https://romedesignawards.com/", verified: true }],
    lastChecked: checked,
    brief: "Rome Design Awards 2026 Season 2 covers packaging, architecture, furniture, product, lighting, interior, and student design. Final deadline September 30, 2026 with later extension possible. Fees vary by stage.",
  },
  {
    id: "retail-design-2026",
    title: "Retail Design Institute International Design Competition",
    translatedTitle: "零售设计协会2026国际设计竞赛",
    organizer: "Retail Design Institute",
    country: "美国", countryCode: "US", language: "英语",
    categories: ["室内设计", "品牌设计", "服务设计"], competitionType: "作品奖项",
    deadline: "2026-07-10", daysLeft: 26, entryFee: -1, feeCurrency: "USD",
    prize: "国际零售设计行业认可与传播", prizeValueUsd: 0,
    eligibility: ["全球零售设计项目", "专业设计团队", "按项目年份要求"], teamAllowed: true,
    summary: "聚焦零售空间、品牌体验和商业环境的国际设计竞赛。",
    sourceGrade: "A",
    sources: [{ name: "Retail Design Institute 官方页面", type: "association", url: "https://www.retaildesigninstitute.org/design-competition", verified: true }],
    lastChecked: checked,
    brief: "Retail Design Institute International Design Competition recognizes retail environments and experiences. Submission deadline July 10, 2026. Review official project eligibility and fee requirements.",
  },
  {
    id: "real-leather-student-2026",
    title: "Real Leather. Stay Different. International Student Design Competition 2026",
    translatedTitle: "Real Leather 2026国际学生设计竞赛",
    organizer: "Leather & Hide Council of America",
    country: "国际", countryCode: "INT", language: "英语",
    categories: ["时尚与纺织", "产品设计", "家具设计"], competitionType: "学生竞赛",
    deadline: "2026-06-30", daysLeft: 16, entryFee: 0, feeCurrency: "USD",
    prize: "获奖制作、展示与行业机会", prizeValueUsd: 0,
    eligibility: ["全球学生", "时尚、配饰、家具等方向", "免费参加"], teamAllowed: false,
    summary: "面向全球学生，以天然皮革和可持续材料议题为核心，覆盖服装、配饰与设计产品。",
    sourceGrade: "B",
    sources: [{ name: "ARTS THREAD 报名页面", type: "media", url: "https://www.artsthread.com/competitions/real-leather-international-student-design-competition-2026", verified: true }],
    lastChecked: checked,
    brief: "Real Leather. Stay Different. International Student Design Competition 2026 is free to enter and open to students. Deadline June 30, 2026. Categories include apparel, accessories, and design. Consult the entry page for prizes and material rules.",
  },
  {
    id: "earth-partner-prize-2026",
    title: "Earth Partner Prize 2026",
    translatedTitle: "Earth Partner 2026青年气候创意奖",
    organizer: "Art Partner / GEF / Re:Wild",
    country: "国际", countryCode: "INT", language: "英语",
    categories: ["摄影与影像", "时尚与纺织", "交互与UI/UX", "社会创新"], competitionType: "Open Call",
    deadline: "2026-10-07", daysLeft: 115, entryFee: 0, feeCurrency: "USD",
    prize: "8名获奖者获 US$10,000 / 5,000 / 2,000", prizeValueUsd: 10000,
    eligibility: ["全球14–30岁", "多种创意媒介", "个人创作者"], teamAllowed: false,
    summary: "面向全球青年，以摄影、电影、时尚、应用、新媒体等形式回应气候危机。",
    sourceGrade: "B",
    sources: [{ name: "Vogue 公告与参赛入口", type: "media", url: "https://www.vogue.com/article/art-partner-unveils-the-2026-earth-partner-prize", verified: true }],
    lastChecked: checked, featured: true,
    brief: "Earth Partner Prize 2026 is open to creatives aged 14–30 worldwide. Accepted media include photography, film, performance, fashion, apps, and new media. Eight winners receive USD 10,000, 5,000, or 2,000. Deadline October 7, 2026.",
  },
];

export function competitionScore(item: CompetitionListing) {
  const free = item.entryFee === 0 ? 100 : 0;
  const prize = Math.min(item.prizeValueUsd / 1000, 60);
  const verified = item.sourceGrade === "A" ? 30 : item.sourceGrade === "B" ? 18 : 5;
  const urgency = item.daysLeft >= 14 && item.daysLeft <= 90 ? 18 : 5;
  return free + prize + verified + urgency;
}

export function getCompetition(id: string) {
  return competitions.find((item) => item.id === id);
}
