import type { CompetitionListing } from "@/lib/types";

export const DESIGN_CATEGORIES = [
  "全部类别",
  "建筑设计",
  "景观设计",
  "城市设计",
  "室内设计",
  "家具设计",
  "产品设计",
  "工业设计",
  "平面设计",
  "品牌设计",
  "包装设计",
  "交互与UI/UX",
  "服务设计",
  "时尚与纺织",
  "珠宝设计",
  "交通工具",
  "照明设计",
  "展陈与装置",
  "摄影与影像",
  "游戏与数字媒体",
  "社会创新",
  "可持续设计",
];

export const COMPETITION_TYPES = [
  "全部类型",
  "概念竞赛",
  "真实项目",
  "作品奖项",
  "学生竞赛",
  "Open Call",
  "政府征集",
  "驻留与奖学金",
];

export const competitions: CompetitionListing[] = [
  {
    id: "seoul-river-rooms",
    title: "Seoul River Rooms International Ideas Competition",
    translatedTitle: "首尔河岸微空间国际概念竞赛",
    organizer: "Seoul Design Foundation",
    country: "韩国",
    countryCode: "KR",
    language: "韩语 / 英语",
    categories: ["建筑设计", "景观设计", "城市设计"],
    competitionType: "概念竞赛",
    deadline: "2026-08-28",
    daysLeft: 75,
    entryFee: 0,
    feeCurrency: "USD",
    prize: "总奖金 ₩60,000,000，首奖 ₩25,000,000",
    prizeValueUsd: 43800,
    eligibility: ["全球开放", "学生可参加", "个人或团队"],
    teamAllowed: true,
    summary: "为汉江沿岸设计可移动、季节性使用的公共微空间，回应休憩、文化活动与气候适应。",
    sourceGrade: "A",
    sources: [
      { name: "主办方竞赛官网", type: "official", url: "#", verified: true },
      { name: "首尔设计基金会", type: "association", url: "#", verified: true },
    ],
    lastChecked: "2026-06-14 08:20 UTC",
    featured: true,
    brief: `Seoul River Rooms International Ideas Competition

Design a family of movable public rooms for the Han River waterfront. Proposals should support rest, performance, informal learning, and seasonal community use while responding to heat, flooding, and easy storage.

Open worldwide to students and professionals. Individuals and multidisciplinary teams of up to five are accepted. No registration fee.

Submit two A1 landscape boards, a 300-word statement, six images, and an optional 45-second animation. Total prize fund is KRW 60,000,000, with KRW 25,000,000 for first prize.

Deadline: August 28, 2026. Judging emphasizes public value, climate response, originality, feasibility, and clarity of communication.`,
  },
  {
    id: "young-furniture-shenzhen",
    title: "Young Furniture Makers 2026",
    translatedTitle: "2026青年家具创想大赛",
    organizer: "深圳家具行业协会",
    country: "中国",
    countryCode: "CN",
    language: "中文",
    categories: ["家具设计", "产品设计", "可持续设计"],
    competitionType: "学生竞赛",
    deadline: "2026-07-31",
    daysLeft: 47,
    entryFee: 0,
    feeCurrency: "CNY",
    prize: "金奖 ¥80,000 + 打样及展览",
    prizeValueUsd: 11100,
    eligibility: ["在校学生", "毕业三年内", "中国及海外院校"],
    teamAllowed: true,
    summary: "面向青年设计师的模块化家具竞赛，关注小户型、可维修结构与本地制造。",
    sourceGrade: "B",
    sources: [
      { name: "深圳家具行业协会公众号", type: "wechat", url: "#", verified: true },
      { name: "报名小程序页面", type: "official", url: "#", verified: false },
    ],
    lastChecked: "2026-06-14 06:35 UTC",
    featured: true,
    brief: `2026青年家具创想大赛

围绕“可生长的家”主题，为城市小户型设计模块化家具。作品应强调可维修、可拆解、本地生产，以及不同人生阶段中的适应能力。

参赛资格：全球高校在校学生及毕业三年内青年设计师。可个人参赛或组成最多3人的团队。不收取报名费。

提交内容：1张A1竖版展板、3张效果图、结构爆炸图、设计说明（300字以内）及原创声明。

金奖奖金人民币80,000元，并提供1:1打样、深圳家具展展览机会。投稿截止：2026年7月31日24:00（北京时间）。`,
  },
  {
    id: "lisbon-empty-ground",
    title: "Lisbon Empty Ground",
    translatedTitle: "里斯本城市缝隙公共空间竞赛",
    organizer: "Ordem dos Arquitectos",
    country: "葡萄牙",
    countryCode: "PT",
    language: "葡萄牙语 / 英语",
    categories: ["城市设计", "景观设计", "社会创新"],
    competitionType: "真实项目",
    deadline: "2026-09-18",
    daysLeft: 96,
    entryFee: 0,
    feeCurrency: "EUR",
    prize: "入围团队各 €12,000，获胜方后续设计合同",
    prizeValueUsd: 54500,
    eligibility: ["需注册建筑师或景观建筑师", "欧盟执业资格", "团队参赛"],
    teamAllowed: true,
    summary: "两阶段真实项目，为里斯本三个闲置街角提出低成本、可快速实施的公共空间系统。",
    sourceGrade: "A",
    sources: [{ name: "葡萄牙建筑师协会", type: "association", url: "#", verified: true }],
    lastChecked: "2026-06-13 21:10 UTC",
    brief: "Lisbon Empty Ground is a two-stage professional design competition for three small public sites. Registered EU architects or landscape architects must lead each team. No entry fee. Shortlisted teams receive EUR 12,000 and the winner enters a design services contract. Deadline: September 18, 2026.",
  },
  {
    id: "new-voices-poster",
    title: "New Voices Poster Biennale",
    translatedTitle: "新声音国际海报双年展",
    organizer: "Warsaw Graphic Arts Centre",
    country: "波兰",
    countryCode: "PL",
    language: "波兰语 / 英语",
    categories: ["平面设计", "品牌设计"],
    competitionType: "Open Call",
    deadline: "2026-07-12",
    daysLeft: 28,
    entryFee: 0,
    feeCurrency: "EUR",
    prize: "€8,000 + 双年展展览与作品集出版",
    prizeValueUsd: 8700,
    eligibility: ["全球开放", "18–35岁", "个人参赛"],
    teamAllowed: false,
    summary: "以“共同语言”为主题征集原创海报，鼓励非拉丁文字系统与跨文化视觉实验。",
    sourceGrade: "A",
    sources: [{ name: "双年展官方网站", type: "official", url: "#", verified: true }],
    lastChecked: "2026-06-14 02:50 UTC",
    featured: true,
    brief: "New Voices Poster Biennale invites designers aged 18–35 worldwide to submit an original poster around the theme Common Language. Entry is free. The EUR 8,000 award includes exhibition and publication. Submit one A2 poster and a short statement by July 12, 2026.",
  },
  {
    id: "helsinki-care-service",
    title: "Designing Care Futures",
    translatedTitle: "赫尔辛基照护未来服务设计挑战",
    organizer: "City of Helsinki",
    country: "芬兰",
    countryCode: "FI",
    language: "芬兰语 / 瑞典语 / 英语",
    categories: ["服务设计", "交互与UI/UX", "社会创新"],
    competitionType: "政府征集",
    deadline: "2026-08-05",
    daysLeft: 52,
    entryFee: 0,
    feeCurrency: "EUR",
    prize: "3支团队各获 €20,000 原型基金",
    prizeValueUsd: 65400,
    eligibility: ["全球团队", "需跨学科团队", "至少一名服务设计师"],
    teamAllowed: true,
    summary: "改善老年人在居家照护、社区服务与数字预约之间的体验，获选方案进入城市原型测试。",
    sourceGrade: "A",
    sources: [{ name: "赫尔辛基市创新采购平台", type: "official", url: "#", verified: true }],
    lastChecked: "2026-06-14 04:05 UTC",
    brief: "The City of Helsinki seeks multidisciplinary teams to improve the experience between home care, community services, and digital appointments for older residents. No fee. Three selected teams receive EUR 20,000 prototype funding. Deadline: August 5, 2026.",
  },
  {
    id: "kyoto-light",
    title: "Kyoto Light and Shadow Award",
    translatedTitle: "京都光影空间设计奖",
    organizer: "Kyoto Lighting Council",
    country: "日本",
    countryCode: "JP",
    language: "日语 / 英语",
    categories: ["照明设计", "室内设计", "展陈与装置"],
    competitionType: "概念竞赛",
    deadline: "2026-09-04",
    daysLeft: 82,
    entryFee: 0,
    feeCurrency: "JPY",
    prize: "大奖 ¥2,000,000 + 京都冬季灯光节落地",
    prizeValueUsd: 13700,
    eligibility: ["全球开放", "学生与专业人士", "团队最多4人"],
    teamAllowed: true,
    summary: "为京都历史街区提出低能耗临时光环境，强调暗夜保护、步行体验与可拆卸安装。",
    sourceGrade: "A",
    sources: [{ name: "京都照明协会官网", type: "association", url: "#", verified: true }],
    lastChecked: "2026-06-13 23:40 UTC",
    brief: "Kyoto Light and Shadow Award seeks a low-energy temporary lighting installation for a historic pedestrian district. Open worldwide, free entry, students and professionals accepted. Grand prize JPY 2,000,000 and festival implementation. Deadline: September 4, 2026.",
  },
  {
    id: "mexico-water-packaging",
    title: "Agua Común Packaging Challenge",
    translatedTitle: "墨西哥公共饮水包装创新挑战",
    organizer: "Diseño para Todos México",
    country: "墨西哥",
    countryCode: "MX",
    language: "西班牙语 / 英语",
    categories: ["包装设计", "品牌设计", "可持续设计"],
    competitionType: "概念竞赛",
    deadline: "2026-07-25",
    daysLeft: 41,
    entryFee: 0,
    feeCurrency: "MXN",
    prize: "MX$250,000 + 企业孵化支持",
    prizeValueUsd: 13900,
    eligibility: ["拉丁美洲居民", "学生与专业人士", "个人或团队"],
    teamAllowed: true,
    summary: "设计可重复使用的公共饮水容器与视觉系统，减少一次性塑料并适应街头补水网络。",
    sourceGrade: "B",
    sources: [{ name: "主办机构官网", type: "official", url: "#", verified: true }],
    lastChecked: "2026-06-14 01:25 UTC",
    brief: "Agua Común asks Latin American designers to create a reusable public water container and visual system. Free entry. MXN 250,000 prize and incubation support. Students and professionals may enter individually or in teams. Deadline: July 25, 2026.",
  },
  {
    id: "melbourne-mobility",
    title: "Last Kilometre 2035",
    translatedTitle: "墨尔本2035最后一公里交通设计赛",
    organizer: "Design Victoria",
    country: "澳大利亚",
    countryCode: "AU",
    language: "英语",
    categories: ["交通工具", "工业设计", "产品设计"],
    competitionType: "学生竞赛",
    deadline: "2026-10-02",
    daysLeft: 110,
    entryFee: 0,
    feeCurrency: "AUD",
    prize: "A$30,000 + 产业导师计划",
    prizeValueUsd: 19800,
    eligibility: ["全球在校学生", "毕业一年内", "个人或2人团队"],
    teamAllowed: true,
    summary: "面向2035年的轻型城市交通工具，重点关注无障碍、共享维护与极端天气使用。",
    sourceGrade: "A",
    sources: [{ name: "Design Victoria", type: "association", url: "#", verified: true }],
    lastChecked: "2026-06-13 18:00 UTC",
    brief: "Last Kilometre 2035 is a free global student mobility competition. Design a lightweight urban vehicle focused on accessibility, shared maintenance, and extreme-weather use. AUD 30,000 prize. Deadline: October 2, 2026.",
  },
  {
    id: "milan-material-residency",
    title: "Waste Is a Beginning",
    translatedTitle: "米兰材料再生设计驻留",
    organizer: "Fondazione Circolare",
    country: "意大利",
    countryCode: "IT",
    language: "意大利语 / 英语",
    categories: ["产品设计", "时尚与纺织", "可持续设计"],
    competitionType: "驻留与奖学金",
    deadline: "2026-07-08",
    daysLeft: 24,
    entryFee: 0,
    feeCurrency: "EUR",
    prize: "8周驻留、€6,000津贴、材料与工作室",
    prizeValueUsd: 6500,
    eligibility: ["全球开放", "毕业五年内", "需提交作品集"],
    teamAllowed: false,
    summary: "支持青年设计师使用米兰制造业边角料完成一件可展览的产品或纺织实验。",
    sourceGrade: "A",
    sources: [{ name: "基金会官网", type: "official", url: "#", verified: true }],
    lastChecked: "2026-06-14 07:10 UTC",
    brief: "Waste Is a Beginning offers an eight-week Milan residency, EUR 6,000 stipend, materials, and studio access for emerging designers working with manufacturing waste. Free application. Deadline: July 8, 2026.",
  },
  {
    id: "canada-indigenous-game",
    title: "Storyworlds Indigenous Game Jam",
    translatedTitle: "加拿大原住民叙事游戏设计征集",
    organizer: "Interactive Arts Canada",
    country: "加拿大",
    countryCode: "CA",
    language: "英语 / 法语",
    categories: ["游戏与数字媒体", "交互与UI/UX", "摄影与影像"],
    competitionType: "Open Call",
    deadline: "2026-08-16",
    daysLeft: 63,
    entryFee: 0,
    feeCurrency: "CAD",
    prize: "C$15,000制作基金 + 发行支持",
    prizeValueUsd: 10900,
    eligibility: ["加拿大居民", "团队至少一名原住民创作者", "2–6人团队"],
    teamAllowed: true,
    summary: "征集以原住民语言、场所与口述传统为核心的短篇互动体验和独立游戏原型。",
    sourceGrade: "A",
    sources: [{ name: "Interactive Arts Canada", type: "association", url: "#", verified: true }],
    lastChecked: "2026-06-13 17:30 UTC",
    brief: "Storyworlds supports short interactive experiences rooted in Indigenous language, place, and oral tradition. Canadian teams of 2–6 must include an Indigenous creator. Free entry, CAD 15,000 production fund. Deadline: August 16, 2026.",
  },
  {
    id: "dubai-interior-award",
    title: "Future Hospitality Interiors Award",
    translatedTitle: "迪拜未来酒店室内设计奖",
    organizer: "Gulf Design Forum",
    country: "阿联酋",
    countryCode: "AE",
    language: "阿拉伯语 / 英语",
    categories: ["室内设计", "家具设计", "照明设计"],
    competitionType: "作品奖项",
    deadline: "2026-08-30",
    daysLeft: 77,
    entryFee: 180,
    feeCurrency: "USD",
    prize: "国际媒体发布、颁奖礼与行业展示，无现金奖金",
    prizeValueUsd: 0,
    eligibility: ["专业设计师", "已完成项目", "项目完成不超过3年"],
    teamAllowed: true,
    summary: "面向已落地酒店与餐饮空间的商业奖项，曝光度较高，但收取报名费且无现金奖金。",
    sourceGrade: "B",
    sources: [{ name: "奖项官网", type: "official", url: "#", verified: true }],
    lastChecked: "2026-06-13 20:15 UTC",
    brief: "Future Hospitality Interiors Award recognizes completed hospitality projects from the past three years. Professional designers only. USD 180 entry fee. No cash prize. Deadline: August 30, 2026.",
  },
  {
    id: "chengdu-community-signage",
    title: "Chengdu Neighbourhood Wayfinding Open Call",
    translatedTitle: "成都社区微更新导视设计公开征集",
    organizer: "成都市社区美空间计划",
    country: "中国",
    countryCode: "CN",
    language: "中文",
    categories: ["平面设计", "城市设计", "社会创新"],
    competitionType: "政府征集",
    deadline: "2026-07-20",
    daysLeft: 36,
    entryFee: 0,
    feeCurrency: "CNY",
    prize: "3组入选方案各 ¥50,000 深化费",
    prizeValueUsd: 20800,
    eligibility: ["中国境内个人或机构", "需相关作品集", "鼓励跨专业团队"],
    teamAllowed: true,
    summary: "为三个老社区建立易读、低成本、可由居民共同维护的导视与公共信息系统。",
    sourceGrade: "B",
    sources: [
      { name: "成都设计公众号", type: "wechat", url: "#", verified: true },
      { name: "政府公开征集附件", type: "official", url: "#", verified: true },
    ],
    lastChecked: "2026-06-14 05:55 UTC",
    brief: "成都社区微更新导视设计公开征集。为三个老社区设计易读、低成本、居民可共同维护的导视与公共信息系统。免报名费，三组入选方案各获人民币50,000元深化费。中国境内个人或机构可报名，鼓励跨专业团队。截止时间：2026年7月20日。",
  },
];

export function competitionScore(item: CompetitionListing) {
  const free = item.entryFee === 0 ? 100 : 0;
  const prize = Math.min(item.prizeValueUsd / 1000, 60);
  const verified = item.sourceGrade === "A" ? 30 : item.sourceGrade === "B" ? 18 : 5;
  const urgency = item.daysLeft >= 21 && item.daysLeft <= 90 ? 18 : 5;
  return free + prize + verified + urgency;
}

export function getCompetition(id: string) {
  return competitions.find((item) => item.id === id);
}
