import type { SavedProject } from "@/lib/types";

function download(filename: string, content: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

const list = (items: string[]) => items.map((item) => `- ${item}`).join("\n");

export function projectToMarkdown(project: SavedProject): string {
  const { analysis } = project;
  const concepts = analysis.concepts
    .map(
      (concept, index) => `## ${index + 1}. ${concept.title}
**Idea:** ${concept.tagline}

**Strategy:** ${concept.strategy}

**Visual mood:** ${concept.visualMood}

**Material palette:** ${concept.materialPalette.join(", ")}

**Why the jury may care:** ${concept.juryAppeal}

### Concept statement
${concept.statement}

### Image prompts
${list(concept.prompts)}

### Board layout
${list(concept.boardLayout)}

### Submission checklist
${concept.checklist.map((item) => `- [ ] **${item.label}:** ${item.detail}`).join("\n")}`,
    )
    .join("\n\n---\n\n");

  return `# ${analysis.competitionTitle}

> Generated by Nugget — Find golden ideas inside messy briefs.

## Brief summary
${analysis.summary}

## Key facts
- **Deadline:** ${analysis.deadline}
- **Eligibility:** ${analysis.eligibility}
- **Entry fee:** ${analysis.entryFee}

## Deliverables
${list(analysis.deliverables)}

## Format requirements
${list(analysis.formatRequirements)}

## Judging criteria
${list(analysis.judgingCriteria)}

## Hidden opportunities
${list(analysis.hiddenOpportunities)}

## Risks
${list(analysis.risks)}

# Concept directions

${concepts}
`;
}

export function exportMarkdown(project: SavedProject) {
  download(`${slug(project.title)}.md`, projectToMarkdown(project), "text/markdown");
}

export function exportJson(project: SavedProject) {
  download(
    `${slug(project.title)}.json`,
    JSON.stringify(project, null, 2),
    "application/json",
  );
}

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
