import type { CompetitionListing } from "@/lib/types";
import type { CompetitionRuleSet } from "@/lib/competition-rules";

export type ProductionConcept = {
  title: string;
  tagline: string;
  strategy: string;
  palette: string[];
  statement: string;
  prompts: string[];
};

export function buildConcepts(competition: CompetitionListing): ProductionConcept[] {
  const domain = competition.categories[0] ?? "设计";
  return [
    {
      title: "Second Life",
      tagline: `把${domain}从一次性成果变成可持续演化的系统。`,
      strategy: `以“拆解、重组、延长寿命”为核心，将竞赛要求转译为清晰的使用场景和可验证的材料策略。`,
      palette: ["深酒红", "自然棕", "亚麻白", "哑光黄铜"],
      statement: `Second Life 不把可持续性当作附加说明，而是让它成为设计的使用方式。方案通过可拆卸部件、清晰连接和可维修构造，使作品能够适应不同场景并延长生命周期。视觉语言保持克制，让材料、结构与人的动作成为表达主体。每一项变化都对应竞赛成果矩阵中的可制造性、原创性和清晰沟通要求，避免只停留在概念图层面。`,
      prompts: [
        `Competition hero visualization for ${competition.title}, concept Second Life, premium editorial presentation, complete proposal clearly visible, refined material detail, plausible construction`,
        `Transformation sequence for ${competition.title}, three configurations shown consistently, clear assembly logic, competition portfolio quality`,
        `Macro construction detail for ${competition.title}, repairable joint, material palette and craftsmanship, photoreal editorial lighting`,
      ],
    },
    {
      title: "Open Framework",
      tagline: "用最少的固定形式，容纳最多的使用变化。",
      strategy: "建立一个稳定的基础框架，通过轻量模块回应不同用户、环境和时间条件。",
      palette: ["炭黑", "沙岩灰", "雾蓝", "暖木色"],
      statement: "Open Framework 将设计理解为一个允许参与者持续调整的基础设施。它不追求单一姿态，而通过明确的主结构和可替换模块，平衡识别度、适应性与实施难度。",
      prompts: [
        `Hero visualization for ${competition.title}, concept Open Framework, adaptable modular system, calm contemporary design, competition quality`,
        `Exploded configuration study for ${competition.title}, modular components and user scenarios, realistic materials`,
        `Context visualization for ${competition.title}, human use and environmental response, coherent design language`,
      ],
    },
    {
      title: "Quiet Signal",
      tagline: "不依赖夸张造型，用精准细节建立记忆点。",
      strategy: "以一个可辨识的连接、界面或空间动作作为核心，其余部分保持安静和高完成度。",
      palette: ["墨绿", "骨白", "石墨", "低饱和金色"],
      statement: "Quiet Signal 把设计资源集中在一个最关键的动作上。通过统一比例、克制色彩和细节精度，让评委先看到清晰主张，再发现完整逻辑。",
      prompts: [
        `Competition hero for ${competition.title}, concept Quiet Signal, restrained iconic gesture, sophisticated editorial visualization`,
        `Detail study for ${competition.title}, precision craftsmanship and coherent material junction`,
        `Full presentation context for ${competition.title}, elegant human-scale use, believable implementation`,
      ],
    },
  ];
}

export function effectiveDeliverables(
  competition: CompetitionListing,
  rules?: CompetitionRuleSet,
) {
  if (rules?.deliverables.length) return rules.deliverables;
  return [
    "3–5张核心视觉或图纸，覆盖整体、使用场景和关键细节",
    "至少一张完整正面或总体视图",
    "一份符合官方字数限制的设计说明",
    "按官方格式导出JPG或PDF并控制文件大小",
    "保留原创过程、参考来源和AI使用记录",
  ];
}

export function packageMarkdown(
  competition: CompetitionListing,
  concept: ProductionConcept,
  deliverables: string[],
) {
  return `# ${competition.translatedTitle}

## Selected concept
${concept.title} — ${concept.tagline}

## Strategy
${concept.strategy}

## Concept statement
${concept.statement}

## Required deliverables
${deliverables.map((item) => `- [x] ${item}`).join("\n")}

## Submission details
- Deadline: ${competition.deadline}
- Entry fee: ${competition.entryFee === 0 ? "Free" : "See official rules"}
- Eligibility: ${competition.eligibility.join("; ")}
- Official source: ${competition.sources[0]?.url ?? "Not available"}

Generated by Nugget. Final authorship, eligibility, technical accuracy, and rule compliance must be confirmed by the entrant.
`;
}
